spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pingpal
    username: pingpal
    password: pingpal123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
